export default {
    "ARS": "$",
    "BOB": "Bs",
    "BRL": "R$",
    "CLF": "UF",
    "CLP": "$",
    "COP": "$",
    "CRC": "₡",
    "CUC": "CUC",
    "CUP": "$",
    "DOP": "$",
    "EUR": "€",
    "GTQ": "Q",
    "HNL": "L",
    "MXN": "$",
    "NIO": "C$",
    "PAB": "B/.",
    "PEN": "S/",
    "PYG": "₲",
    "USD": "U$S",
    "UYU": "$",
    "VEF": "Bs.",
    "VES": "Bs."
}
